apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component1
    app.kubernetes.io/part-of: m5-app
  name: component1
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: component1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: component1
    spec:
      containers:
      - image: quay.io/jbieren/test
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
